# Generated by Django 5.1.6 on 2025-03-07 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20250307_1114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='vacation_balance',
        ),
    ]
