# Generated by Django 5.1.6 on 2025-03-07 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20250307_1237'),
    ]

    operations = [
    ]
