# Generated by Django 5.1.6 on 2025-03-10 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_event_description_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetracking',
            name='break_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='break_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timetracking',
            name='total_break_time',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
