# Generated by Django 5.1.6 on 2025-03-10 10:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_timetracking_break_end_timetracking_break_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetracking',
            name='break_end',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='break_start',
        ),
        migrations.RemoveField(
            model_name='timetracking',
            name='total_break_time',
        ),
        migrations.CreateModel(
            name='BreakTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_break_time', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('time_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breaks', to='accounts.timetracking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
