# Generated by Django 5.1.6 on 2025-03-10 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_timetracking_break_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BreakTracking',
        ),
    ]
