# Generated by Django 5.1.6 on 2025-03-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_delete_breaktracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('CEO', 'CEO'), ('HR', 'HR'), ('Team Lead', 'Team Lead'), ('Deputy Lead', 'Deputy Lead'), ('Employee', 'Employee')], default='Employee', max_length=20),
        ),
    ]
